export const LOGIN_ATTEMING='LOGIN_ATTEMING';
export const LOGIN_FAILED='LOGIN_FAILED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';

export const SIGNUP_ATTEMING='SIGNUP_ATTEMING';
export const SIGNUP_FAILED=  'SIGNUP_FAILED';
export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS';

export const FACEBOOKLOGIN_ATTEMING='FACEBOOKLOGIN_ATTEMING';
export const FACEBOOKLOGIN_FAILED=  'FACEBOOKLOGIN_FAILED';
export const FACEBOOKLOGIN_SUCCESS= 'FACEBOOKLOGIN_SUCCESS';



export const GETALL_SUCCESS= 'GETALL_SUCCESS';
export const GETALL_ATTEMING= 'GETALL_ATTEMING';
export const GETONE_SUCCESS= 'GETONE_SUCCESS';
